//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProduto
    {
        public int ID { get; set; }
        public int PedidoID { get; set; }
        public int ProdutoID { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> PrecoUnitario { get; set; }
    }
}
