//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosWeb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PedidosWeb.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao processar a operação. Entre em contato com o administrador do sistema..
        /// </summary>
        internal static string ContateAdminstrador {
            get {
                return ResourceManager.GetString("ContateAdminstrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item excluído com sucesso..
        /// </summary>
        internal static string ItemExcluidoSucesso {
            get {
                return ResourceManager.GetString("ItemExcluidoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item salvo com sucesso..
        /// </summary>
        internal static string ItemSalvoSucesso {
            get {
                return ResourceManager.GetString("ItemSalvoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um item para fazer a exclusão..
        /// </summary>
        internal static string ItemSelecioneExclusao {
            get {
                return ResourceManager.GetString("ItemSelecioneExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido salvo com sucesso..
        /// </summary>
        internal static string PedidoSalvoSucesso {
            get {
                return ResourceManager.GetString("PedidoSalvoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quantidade deve ser maior que zero..
        /// </summary>
        internal static string QuantidadeMaiorZero {
            get {
                return ResourceManager.GetString("QuantidadeMaiorZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um produto..
        /// </summary>
        internal static string SelecioneProduto {
            get {
                return ResourceManager.GetString("SelecioneProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um usuário cadastrado com o login {0}.
        /// </summary>
        internal static string UsuarioExistente {
            get {
                return ResourceManager.GetString("UsuarioExistente", resourceCulture);
            }
        }
    }
}
